name: doage # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '2.15+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: dosage is a comic strip downloader and archiver 
description: |
  dosage is a comic strip downloader and archiver written in Python

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
    dosage:
        command: bin/dosage

parts:
  dosage:
    source: https://github.com/webcomics/dosage.git
    source-type: git
    # See 'snapcraft plugins'
    plugin: python
